{{- if .Values.podSecurityPolicy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "prometheus-mongodb-query-exporter.fullname" . }}
  {{- with ( include "prometheus-mongodb-query-exporter.labels" . ) }}
  labels:
    {{- . }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "prometheus-mongodb-query-exporter.fullname" . }}
subjects:
- kind: ServiceAccount
  {{- if .Values.serviceAccount.create  }}
  name: {{ template "prometheus-mongodb-query-exporter.fullname" . }}
  {{- else }}
  name: {{ .Values.serviceAccount.name }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
{{- end }}
