{{- if .Values.podSecurityPolicy.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "mongodb-query-exporter.fullname" . }}
  {{- with ( include "mongodb-query-exporter.labels" . ) }}
  labels:
    {{- . }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "mongodb-query-exporter.fullname" . }}
{{- end }}
