{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-mongodb-query-exporter.serviceAccountName" . }}
  {{- with ( include "prometheus-mongodb-query-exporter.labels" . ) }}
  labels:
    {{- . }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
