on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15'
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF##*/}
      - name: Unit tests & coverage
        run: |
          make test
      - name: Full build
        run: make docker DOCKER_IMAGE_TAG=${{ steps.get_version.outputs.VERSION }}
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
      - name: Create beta Release
        id: create_beta_release
        if: startsWith(github.ref, 'refs/tags/v') && (contains(github.ref, '-beta') || contains(github.ref, '-alpha'))
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: true
      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-beta') && !contains(github.ref, '-alpha')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
      - name: Upload beta Release Asset
        id: upload-beta-release-asset
        if: startsWith(github.ref, 'refs/tags/v') && (contains(github.ref, '-beta') || contains(github.ref, '-alpha'))
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_beta_release.outputs.upload_url }}
          asset_path: ./mongodb_query_exporter
          asset_name: mongodb_query_exporter
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        id: upload-release-asset
        if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-beta') && !contains(github.ref, '-alpha')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mongodb_query_exporter
          asset_name: mongodb_query_exporter
          asset_content_type: application/octet-stream
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: raffis/mongodb-query-exporter
      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          charts_dir: ./chart
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
